train:
    folder: 'dummy'
    device: 'cuda'
    parallel: False
    resolution: 512
    batch_size: 16
    num_workers: 8
    epochs: 30
    

optimizer:
    lr: 0.0002
    beta_1: 0.5
    beta_2: 0.9999
    amsgrad: False

log:
    log_interval: 5
    num_samples: 8
    save_freq: 1
    save_everything: yes # whether save all modules or just generator
    chkpt_dir: 'chkpt'
    log_dir: 'tensorboard'

dataset:
    pets: 'https://www.robots.ox.ac.uk/~vgg/data/pets/data/images.tar.gz'
    flowers_102: 'https://www.robots.ox.ac.uk/~vgg/data/flowers/102/102flowers.tgz'
    birds: 'https://www.robots.ox.ac.uk/~vgg/data/bicos/data/birds.tar'
    sculptures: 'https://www.robots.ox.ac.uk/~vgg/data/sculptures6k/sculptures6k.tar.gz'